### ISSUE TITLE
Did not find generate_gt_info.py in tracking part

### ISSUE THREAD

**Issue by wusongyuan** [PJLab-ADG/DetZero#13]
As mentioned in Intro of tracking, there is a script named "generate_gt_info.py" to generate gt_infos pickle files. However, I did not find that script in the project.

**Comment by SISTMrL** [comment]
hello, could you please provide the generate_gt_info.py scripts?

**Comment by superkoma** [comment]
- We forgot to delete the instruction of 'generate_gt_info.py' in the tracking part.
- We support to use the gt_info (waymo_infos_train.pkl, waymo_infos_val.pkl) generated in detection module for tracking module currently.
- Please feel free to first generate the gt infos based on instructions of data preprocessing.

**Comment by wusongyuan** [comment]
> * We forgot to delete the instruction of 'generate_gt_info.py' in the tracking part.
> * We support to use the gt_info (waymo_infos_train.pkl, waymo_infos_val.pkl) generated in detection module for tracking module currently.
> * Please feel free to first generate the gt infos based on instructions of data preprocessing.

Thanks for your reply. When I try to generate infos for tracking, there is an error "KeyError: 'boxes_lidar'". I suppose the reason is that all the annotations in pkl that generate in detection were stored in "gt_boxes_lidar" key. However, the script in tracking was trying to parse the annotations in the key named "boxes_lidar".

--------------------------------------------------------------------------------------------------------------------------------------------------------------------
python -u run_track.py --cfg_file cfgs/tk_model_cfgs/waymo_detzero_track.yaml --data_path ../../data/waymo/waymo_infos_train.pkl --workers 4 --split train

2023-09-20 09:36:02,748   INFO  ----------------------------          DetZero Tracking Module          ----------------------------
2023-09-20 09:36:02,748   INFO  LOCAL_RANK                    : 0
2023-09-20 09:36:02,748   INFO  DATA_CONFIG                    
2023-09-20 09:36:02,748   INFO  DATASET                       : WaymoTrackDataset
2023-09-20 09:36:02,748   INFO  DATA_PATH                     : ../../data/waymo
2023-09-20 09:36:02,748   INFO  PROCESSED_DATA_TAG            : waymo_processed_data
2023-09-20 09:36:02,748   INFO  CLASS_NAME                    : ['Vehicle', 'Pedestrian', 'Cyclist']
2023-09-20 09:36:02,748   INFO  DATA_PROCESSOR                : [{'NAME': 'heading_process'}, {'NAME': 'overlap_box_filter', 'METHOD': 'max_score', 'CLASS_THRESHOLD': {'Vehicle': 0.3, 'Pedestrian': 0.2, 'Cyclist': 0.2}}, {'NAME': 'transform_to_global'}]
2023-09-20 09:36:02,748   INFO  _BASE_CONFIG_                 : cfgs/tk_dataset_cfgs/waymo_dataset.yaml
2023-09-20 09:36:02,748   INFO  MODEL                          
2023-09-20 09:36:02,748   INFO  NAME                          : DetZeroTracker
2023-09-20 09:36:02,748   INFO  TRACKING                       
2023-09-20 09:36:02,748   INFO  NAME                          : TrackManager
2023-09-20 09:36:02,748   INFO  FILTER                         
2023-09-20 09:36:02,748   INFO  NAME                          : KalmanFilter
2023-09-20 09:36:02,748   INFO  X_DIM                         : 5
2023-09-20 09:36:02,748   INFO  Z_DIM                         : 3
2023-09-20 09:36:02,748   INFO  Q                             : [5, 15]
2023-09-20 09:36:02,748   INFO  P                             : [50, 1000]
2023-09-20 09:36:02,748   INFO  R                             : 0.1
2023-09-20 09:36:02,748   INFO  DELTA_T                       : 0.1
2023-09-20 09:36:02,748   INFO  TRACK_AGE                      
2023-09-20 09:36:02,748   INFO  BIRTH_AGE                     : 1
2023-09-20 09:36:02,748   INFO  DEATH_AGE                     : -1
2023-09-20 09:36:02,748   INFO  DATA_ASSOCIATION               
2023-09-20 09:36:02,748   INFO  CLASS_NAME                    : ['Vehicle', 'Pedestrian', 'Cyclist']
2023-09-20 09:36:02,748   INFO  DISTINGUISH_CLASS             : True
2023-09-20 09:36:02,748   INFO  DISTANCE_METHOD               : IoUBEV
2023-09-20 09:36:02,748   INFO  ASSIGNMENT_METHOD             : GNN
2023-09-20 09:36:02,748   INFO  STAGE                          
2023-09-20 09:36:02,748   INFO  NAME                          : two_stage
2023-09-20 09:36:02,748   INFO  FIRST_STAGE                    
2023-09-20 09:36:02,748   INFO  DIST_THRESHOLD                : [0.2, 0.1, 0.1]
2023-09-20 09:36:02,748   INFO  SECOND_STAGE                   
2023-09-20 09:36:02,748   INFO  SCORE_THRESHOLD               : [0.1, 0.1, 0.1]
2023-09-20 09:36:02,748   INFO  POINT_THRESHOLD               : [0, 0, 0]
2023-09-20 09:36:02,748   INFO  DIST_THRESHOLD                : [0.3, 0.15, 0.15]
2023-09-20 09:36:02,748   INFO  TRACK_MERGE                    
2023-09-20 09:36:02,749   INFO  ENABLE                        : True
2023-09-20 09:36:02,749   INFO  CLASS_NAME                    : ['Vehicle', 'Pedestrian', 'Cyclist']
2023-09-20 09:36:02,749   INFO  CLASS_THRESHOLD               : [0.5, 0.4, 0.4]
2023-09-20 09:36:02,749   INFO  REVERSE_TRACKING               
2023-09-20 09:36:02,749   INFO  ENABLE                        : True
2023-09-20 09:36:02,749   INFO  POST_PROCESS                   
2023-09-20 09:36:02,749   INFO  NAME                          : PostProcessor
2023-09-20 09:36:02,749   INFO  CONFIG_LIST                   : [{'NAME': 'empty_track_delete', 'LEAST_AGE': 5, 'END_REMOVE': True}, {'NAME': 'velocity_optimize', 'HEADER_LENGTH': 3}, {'NAME': 'motion_classify'}, {'NAME': 'static_drift_eliminate'}]
2023-09-20 09:36:02,749   INFO  REFINING                       
2023-09-20 09:36:02,749   INFO  IOU_THRESHOLDS                 
2023-09-20 09:36:02,749   INFO  Vehicle                       : 0.3
2023-09-20 09:36:02,749   INFO  Pedestrian                    : 0.1
2023-09-20 09:36:02,749   INFO  Cyclist                       : 0.1
2023-09-20 09:36:02,749   INFO  ROOT_DIR                      : /detzero/tracking
2023-09-20 09:36:02,749   INFO  CFG_FILE                      : cfgs/tk_model_cfgs/waymo_detzero_track.yaml
2023-09-20 09:36:02,749   INFO  DATA_PATH                     : ../../data/waymo/waymo_infos_train.pkl
2023-09-20 09:36:02,749   INFO  WORKERS                       : 4
2023-09-20 09:36:02,749   INFO  BATCH_SIZE                    : 8
2023-09-20 09:36:02,749   INFO  SPLIT                         : train
2023-09-20 09:36:02,749   INFO  SAVE_LOG                      : False
2023-09-20 09:36:02,749   INFO  --------------------------          Initialize WaymoTrackDataset          --------------------------
2023-09-20 09:36:02,899   INFO  ----------------------------          Running Tracking Module!          ----------------------------
  0%|                                                                                                                 | 0/1 [00:00<?, ?it/s]
  0%|                                                                                                                 | 0/1 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "run_track.py", line 72, in <module>
    main()
  File "run_track.py", line 60, in main
    run_model(
  File "/detzero/tracking/detzero_track/models/__init__.py", line 37, in run_model
    for idx, (seq_names, data_dicts) in enumerate(pbar):
  File "/home/miniconda3/envs/detzero/lib/python3.8/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/miniconda3/envs/detzero/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/miniconda3/envs/detzero/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/miniconda3/envs/detzero/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/miniconda3/envs/detzero/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/miniconda3/envs/detzero/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/miniconda3/envs/detzero/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/miniconda3/envs/detzero/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/detzero/tracking/detzero_track/datasets/waymo_dataset.py", line 81, in __getitem__
    det_data, drop_data = self.data_processor.forward(data_dict=det_infos)
  File "/detzero/tracking/detzero_track/datasets/data_processor.py", line 34, in forward
    curr_data = cur_processor(data_dict=curr_data)
  File "/detzero/tracking/detzero_track/datasets/data_processor.py", line 91, in transform_to_global
    boxes_lidar = data_dict["boxes_lidar"]
KeyError: 'boxes_lidar'

**Comment by Kailthen** [comment]
同样的异常信息，您有进展吗

**Comment by zorinasu** [comment]
should use detection model result pkl path after --data_path
