### ISSUE TITLE
track error

### ISSUE THREAD

**Issue by rockywind** [PJLab-ADG/DetZero#18]
Hi, thank you for sharing the great work.
I met the error below when I run the track script.
The error is below.
````
/SHFP12/xiaoquan.wang/01_bev/DetZero/detection/output/SHFP12/xiaoquan.wang/01_bev/DetZero/detection/tools/cfgs/det_model_cfgs/centerpoint_1sweep_my/default/eval/epoch_30/val/result.pkl
[57] 2023-09-27 01:37:53,677   INFO  WORKERS                       : 16
[58] 2023-09-27 01:37:53,677   INFO  BATCH_SIZE                    : 8
[59] 2023-09-27 01:37:53,677   INFO  SPLIT                         : val
[60] 2023-09-27 01:37:53,677   INFO  SAVE_LOG                      : False
[61] 2023-09-27 01:37:53,677   INFO  --------------------------          Initialize WaymoTrackDataset          --------------------------
[62] 2023-09-27 01:38:01,169   INFO  ----------------------------          Running Tracking Module!          ----------------------------
[63] 
[64]   0%|                                                                                                                | 0/26 [00:00<?, ?it/s]
[65]   4%|###8                                                                                                 | 1/26 [06:50<2:51:01, 410.45s/it]
[66]   8%|#######7                                                                                             | 2/26 [10:01<1:52:36, 281.50s/it]
[67]  12%|###########6                                                                                         | 3/26 [12:02<1:19:48, 208.18s/it]
[68]  15%|###############5                                                                                     | 4/26 [15:47<1:18:40, 214.59s/it]
[69]  19%|###################4                                                                                 | 5/26 [20:05<1:20:39, 230.43s/it]
[70]  23%|#######################3                                                                             | 6/26 [22:55<1:09:57, 209.87s/it]
[71]  27%|###########################1                                                                         | 7/26 [27:10<1:11:06, 224.54s/it]
[72]  31%|###############################6                                                                       | 8/26 [29:36<59:54, 199.70s/it]
[73]  35%|###################################6                                                                   | 9/26 [32:16<53:03, 187.26s/it]
[74]  38%|#######################################2                                                              | 10/26 [35:33<50:42, 190.18s/it]
[75]  38%|#######################################2                                                              | 10/26 [36:05<57:44, 216.54s/it]
[76] concurrent.futures.process._RemoteTraceback: 
[77] """
[78] Traceback (most recent call last):
[79]   File "/opt/conda/envs/detzero/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
[80]     r = call_item.fn(*call_item.args, **call_item.kwargs)
[81]   File "/opt/conda/envs/detzero/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
[82]     return [fn(*args) for args in chunk]
[83]   File "/opt/conda/envs/detzero/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
[84]     return [fn(*args) for args in chunk]
[85]   File "/defaultShare/SHFP12/xiaoquan.wang/01_bev/DetZero/tracking/detzero_track/models/detzero_tracker.py", line 45, in forward
[86]     data_dict = module.forward(data_dict=data_dict)
[87]   File "/defaultShare/SHFP12/xiaoquan.wang/01_bev/DetZero/tracking/detzero_track/models/tracking_modules/track_manager.py", line 132, in forward
[88]     frm_id, data_dict[frm_id], frm_tracks[frm_id], reverse_tracks
[89] KeyError: '0'
[90] """
[91] 
[92] The above exception was the direct cause of the following exception:
[93] 
[94] Traceback (most recent call last):
[95]   File "run_track.py", line 72, in <module>
[96]     main()
[97]   File "run_track.py", line 60, in main
[98]     run_model(
[99]   File "/defaultShare/SHFP12/xiaoquan.wang/01_bev/DetZero/tracking/detzero_track/models/__init__.py", line 38, in run_model
[100]     model_outputs = multi_processing(
[101]   File "/defaultShare/SHFP12/xiaoquan.wang/01_bev/DetZero/utils/detzero_utils/common_utils.py", line 298, in multi_processing
[102]     results = [x for x in executor.map(function, data_dict, chunksize=workers)]
[103]   File "/defaultShare/SHFP12/xiaoquan.wang/01_bev/DetZero/utils/detzero_utils/common_utils.py", line 298, in <listcomp>
[104]     results = [x for x in executor.map(function, data_dict, chunksize=workers)]
[105]   File "/opt/conda/envs/detzero/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
[106]     for element in iterable:
[107]   File "/opt/conda/envs/detzero/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
[108]     yield fs.pop().result()
[109]   File "/opt/conda/envs/detzero/lib/python3.8/concurrent/futures/_base.py", line 444, in result
[110]     return self.__get_result()
[111]   File "/opt/conda/envs/detzero/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
[112]     raise self._exception
[113] KeyError: '0'
````
The run track script is below.
````
python  run_track.py \
--cfg_file cfgs/tk_model_cfgs/waymo_detzero_track_my.yaml \
--data_path /SHFP12/xiaoquan.wang/01_bev/DetZero/detection/output/SHFP12/xiaoquan.wang/01_bev/DetZero/detection/tools/cfgs/det_model_cfgs/centerpoint_1sweep_my/default/eval/epoch_30/val/result.pkl \
--workers 16 --split val
````

**Comment by PrinceVictor** [comment]
- From the log, it seems that when frm_id=='0', the online_track_module function does not have any tracks output, which results frm_tracks does not contain the key '0'.
- A temporary solution for this issue is to skip the reverse_tracking_module function when the frm_tracks does not contain the key '0'.
- We will conduct further testing to ensure it work here well.

**Comment by rockywind** [comment]
Thanks a lot!

**Comment by RaymondByc** [comment]
I met the same error. Could you tell me how to solve it?

**Comment by PrinceVictor** [comment]
- From the log, it seems that when frm_id=='0', the online_track_module function does not have any tracks output, which results frm_tracks does not contain the key '0'.
- A temporary solution for this issue is to skip the reverse_tracking_module function when the frm_tracks does not contain the key '0'.
- We will conduct further testing to ensure it work here well.

**Comment by Furchtlos001** [comment]
I met the same error. Could you tell me how to solve it? @RaymondByc @rockywind
