### ISSUE TITLE
KeyError: 'Cyclist'

### ISSUE THREAD

**Issue by reynerliu** [PJLab-ADG/DetZero#48]
here is the error when I use the detection module to train.
Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main()
  File "train.py", line 112, in main
    train_set, train_loader, train_sampler = build_dataloader(
  File "/home/lzc/DetZero/detection/detzero_det/datasets/__init__.py", line 44, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
  File "/home/lzc/DetZero/detection/detzero_det/datasets/waymo/waymo_dataset.py", line 21, in __init__
    super().__init__(dataset_cfg, class_names, training, root_path, logger)
  File "/home/lzc/DetZero/detection/detzero_det/datasets/dataset.py", line 40, in __init__
    self.data_augmentor = self.init_data_augmentor()
  File "/home/lzc/DetZero/detection/detzero_det/datasets/waymo/waymo_dataset.py", line 42, in init_data_augmentor
    data_augmentor = DataAugmentor(
  File "/home/lzc/DetZero/detection/detzero_det/datasets/augmentor/data_augmentor.py", line 24, in __init__
    cur_augmentor = getattr(self, cur_cfg.NAME)(config=cur_cfg)
  File "/home/lzc/DetZero/detection/detzero_det/datasets/augmentor/data_augmentor.py", line 28, in gt_sampling
    db_sampler = database_sampler.DataBaseSampler(
  File "/home/lzc/DetZero/detection/detzero_det/datasets/augmentor/database_sampler.py", line 27, in __init__
    [self.db_infos[cur_class].extend(infos[cur_class]) for cur_class in class_names]
  File "/home/lzc/DetZero/detection/detzero_det/datasets/augmentor/database_sampler.py", line 27, in <listcomp>
    [self.db_infos[cur_class].extend(infos[cur_class]) for cur_class in class_names]
KeyError: 'Cyclist'

What should I do?

**Comment by reynerliu** [comment]
Here is my command: python train.py --cfg_file cfgs/det_model_cfgs/centerpoint_1sweep.yaml

**Comment by superkoma** [comment]
Have you finished the ground-truth sampling data creation before?

**Comment by suibiandou** [comment]
I got the same error, KeyError: 'Vehicle'
********************************************************************************************************
Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main()
  File "train.py", line 112, in main
    train_set, train_loader, train_sampler = build_dataloader(
  File "/home/xuli/work/DetZero/detection/detzero_det/datasets/__init__.py", line 44, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
  File "/home/xuli/work/DetZero/detection/detzero_det/datasets/waymo/waymo_dataset.py", line 21, in __init__
    super().__init__(dataset_cfg, class_names, training, root_path, logger)
  File "/home/xuli/work/DetZero/detection/detzero_det/datasets/dataset.py", line 40, in __init__
    self.data_augmentor = self.init_data_augmentor()
  File "/home/xuli/work/DetZero/detection/detzero_det/datasets/waymo/waymo_dataset.py", line 42, in init_data_augmentor
    data_augmentor = DataAugmentor(
  File "/home/xuli/work/DetZero/detection/detzero_det/datasets/augmentor/data_augmentor.py", line 24, in __init__
    cur_augmentor = getattr(self, cur_cfg.NAME)(config=cur_cfg)
  File "/home/xuli/work/DetZero/detection/detzero_det/datasets/augmentor/data_augmentor.py", line 28, in gt_sampling
    db_sampler = database_sampler.DataBaseSampler(
  File "/home/xuli/work/DetZero/detection/detzero_det/datasets/augmentor/database_sampler.py", line 27, in __init__
    [self.db_infos[cur_class].extend(infos[cur_class]) for cur_class in class_names]
  File "/home/xuli/work/DetZero/detection/detzero_det/datasets/augmentor/database_sampler.py", line 27, in <listcomp>
    [self.db_infos[cur_class].extend(infos[cur_class]) for cur_class in class_names]
KeyError: 'Vehicle'
*********************************************************************************************************
i finished the ground-truth sampling data creation, and I got "waymo_dbinfos_train_sampled_1_sweep_1.pkl"


After $python -m detzero_det.datasets.waymo.waymo_preprocess --cfg_file tools/cfgs/det_dataset_cfgs/waymo_1sweep.yaml --func create_waymo_database

2024-03-29 18:16:55.560559: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2024-03-29 18:16:56,360   INFO  Loading Waymo dataset
2024-03-29 18:16:56,921   INFO  Total skipped info 202
2024-03-29 18:16:56,922   INFO  Total samples for Waymo dataset: 0
---------------Start create groundtruth database for data augmentation---------------
2024-03-29 18:16:56,927   INFO  Loading Waymo dataset
2024-03-29 18:16:59,150   INFO  Total skipped info 798
2024-03-29 18:16:59,150   INFO  Total samples for Waymo dataset: 0
---------------Data preparation Done---------------

Have you solved the problem? @reynerliu
