### ISSUE TITLE
ModuleNotFoundError: No module named 'detzero_det.version'

### ISSUE THREAD

**Issue by llz666ha** [PJLab-ADG/DetZero#59]
when I run:  python -m detzero_det.datasets.waymo.waymo_preprocess --cfg_file tools/cfgs/det_dataset_cfgs/waymo_one_sweep.yaml --func create_waymo_infos
Error：
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/miniconda3/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/autodl-tmp/detzero/DetZero/detection/detzero_det/__init__.py", line 4, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'detzero_det.version'

Is it a problem with the dataset? I use one tar of waymo perception v1.4

**Comment by llz666ha** [comment]
sorry,I missed 1 step
